# This is a basic workflow to help you get started with Actions

name: test

# Controls when the workflow will run
on:
  #schedule every minute run
  push:
  schedule:
  - cron: "* * * * *"
  
  # Triggers the workflow on push or pull request events but only for the master branch
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  bot:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: commit
        run: |
          find . -mtime +7 -name '*.json' rm {} \;
          curl -s "https://prod-site-api.dwnews.com/v2/feed/zone/10000117?limit=10&bucketId=00000" -o 10000117-`date "+%s"`.json
          curl -s "https://prod-site-api.dwnews.com/v2/feed/zone/10000118?limit=10&bucketId=00000" -o 10000118-`date "+%s"`.json
          curl -s "https://prod-site-api.dwnews.com/v2/feed/zone/10000120?limit=10&bucketId=00000" -o 10000120-`date "+%s"`.json
          curl -s "https://prod-site-api.dwnews.com/v2/feed/zone/10000119?limit=10&bucketId=00000" -o 10000119-`date "+%s"`.json
          curl -s "https://prod-site-api.dwnews.com/v2/feed/zone/10000123?limit=10&bucketId=00000" -o 10000123-`date "+%s"`.json
          curl -s "https://prod-site-api.dwnews.com/v2/feed/zone/10000153?limit=10&bucketId=00000" -o 10000153-`date "+%s"`.json
          git config --global user.email "jluckbord@gmail.com"
          git config --global user.name "jluckbord"
          git add .
          git commit -m "update" -a || exit 0
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
#       - name: Run a one-line script
#         run: echo Hello, world!

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
#       - name: www.zncpxt.com
#         run: curl -s https://www.google.com/
# #         run: curl -s http://www.zncpxt.com:8080/
